### ISSUE TITLE
Nuxt Bridge Build Error involving script setup 

### ISSUE THREAD

**Issue by wesley3295** [antfu/unplugin-vue2-script-setup#151]
Unfortunately, I can only supply the error and package.json. Our software involves handling private information so the application cannot be replicated, my apologies.
```
{
  "name": "",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "node --max-old-space-size=16000 node_modules/nuxi/bin/nuxi.mjs build",
    "analyze": "nuxt build --analyze",
    "start": "nuxi preview",
    "test": "vitest",
    "test-ui": "vitest --ui",
    "coverage": "vitest run --coverage",
   
  "dependencies": {
    "axios-retry": "^3.1.9",
    "@koumoul/vjsf": "^2.10.3",
    "@nuxtjs/auth-next": "5.0.0-1617968180.f699074",
    "@nuxtjs/axios": "^5.13.1",
    "@vueuse/core": "^7.5.4",
    "core-js": "^3.11.1",
    "dotenv": "^16.0.0",
    "jsonwebtoken": "^8.5.1",
    "ldap-authentication": "^2.2.7",
    "lodash-es": "^4.17.21",
    "marklogic": "^2.6.0",
    "multer": "^1.4.3",
    "nanoid": "^3.3.1",
    "nuxt-edge": "latest",
    "parse-duration": "^1.0.0",
    "typescript": "^4.5.5",
    "vue-toastification": "1.7.11",
    "vuedraggable": "^2.24.3",
    "zingchart": "^2.9.7",
    "zingchart-vue": "^2.0.3"
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27498038.f18e68b",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/vuetify": "^1.12.1",
    "@vitest/ui": "^0.10.0",
    "@vue/test-utils": "^1.2.1",
    "@vueuse/nuxt": "^7.6.1",
    "babel-core": "7.0.0-bridge.0",
    "c8": "^7.11.0",
    "deepmerge": "^4.2.2",
    "eslint-config-prettier": "^8.3.0",
    "prettier": "^2.3.2",
    "sass": "^1.47.0",
    "sass-loader": "^10.3.1",
    "std-env": "^3.0.1",
    "supertest": "^6.2.2",
    "vitest": "^0.10.0",
    "webpack": "^4.46.0"
  }
}

```
```
debug mode: ESC[90mundefinedESC[39m



FATAL  Cannot read properties of undefined (reading 'nuxt')



 at scriptSetupModule (node_modules/unplugin-vue2-script-setup/dist/nuxt.mjs:843:64)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setupScriptSetup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1264:3)
  at async setup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1311:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:177:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:349:5)




ERROR  Cannot read properties of undefined (reading 'nuxt')



 at scriptSetupModule (node_modules/unplugin-vue2-script-setup/dist/nuxt.mjs:843:64)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setupScriptSetup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1264:3)
  at async setup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1311:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:177:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:349:5)
```

**Comment by xiaoxiangmoe** [comment]
Hi, @wesley3295 
The configuration of unplugin-vue2-script-setup is did by nuxt, so you should create a bug in nuxt and provide a minimal reproduction demo to them.
