### ISSUE TITLE
Error: Cannot find module 'unplugin-vue2-script-setup/webpack'

### ISSUE THREAD

**Issue by duguangyan** [antfu/unplugin-vue2-script-setup#48]
// vue.config.js

module.exports = {
  configureWebpack: {
    plugins: [
      require('unplugin-vue2-script-setup/webpack')({ /* options */ }),
    ],
  },
}
linux => npm run build:sit
Error: Cannot find module 'unplugin-vue2-script-setup/webpack'

**Comment by duguangyan** [comment]
[Pipeline] sh
+ npm run build:sit

> kaibang-eam@1.0.1 build:sit /data/jenkins/workspace/kaibang-eam-web-test
> vue-cli-service build --mode sit

 ERROR  Error loading vue.config.js:
 ERROR  Error: Cannot find module 'unplugin-vue2-script-setup/webpack'
Error: Cannot find module 'unplugin-vue2-script-setup/webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/jenkins/workspace/kaibang-eam-web-test/vue.config.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE

**Comment by duguangyan** [comment]
linux jenkins 构建 错误 ，但在window上面构建就没有问题

**Comment by allenchannn** [comment]
请问这个问题后面解决了么

**Comment by xiaoxiangmoe** [comment]
能给一个可复现的 repo 吗？@allenchannn

https://github.com/xiaoxiangmoe/vue2-vuecli-demo

我这个 demo 跑得是好的

**Comment by zhenizhui** [comment]
@xiaoxiangmoe  win 系统下，切换 node 环境为 v12.16.1 就会复现了
